title: Beyond the Literal: Unmasking Sarcasm’s Signature on Reddit

description: Report for Document Ananlysis semester project.  
show_downloads: True
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - REPORT.md

theme: jekyll-theme-minimal

