title: "Beyond the Literal: Unmasking Sarcasm’s Signature on Reddit"

description: "Report for the semester project in 'Document Analysis: Computational Methods' 2025"  
show_downloads: True
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - REPORT.md

theme: jekyll-theme-minimal

